apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
  labels:
    app: goapp
spec:
  type: LoadBalancer
  selector:
    app: goapp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000